
-- 검색
SELECT * FROM ORDERS;
SELECT * FROM ROOM;
SELECT * FROM USER;

-- 방 데이터
insert into ROOM(ROOM_ID, CREATED_BY, CREATED_DATE, CURR_NUM_OF_PEOPLE, CURRENT_AMOUNT, GATHERING_PLACE, MAXIMUM_PEOPLE, MINIMUM_ORDER_AMOUNT, TITLE)
values(1L, '김민수', now(), 0, 0, '디지털관', 10, 10000, '공차');
insert into ROOM(ROOM_ID, CREATED_BY, CREATED_DATE, CURR_NUM_OF_PEOPLE, CURRENT_AMOUNT, GATHERING_PLACE, MAXIMUM_PEOPLE, MINIMUM_ORDER_AMOUNT, TITLE)
values(2L, '민수킴', now(), 0, 0, '테크노관', 10, 10000, '맘터 같이 먹자');
insert into ROOM(ROOM_ID, CREATED_BY, CREATED_DATE, CURR_NUM_OF_PEOPLE, CURRENT_AMOUNT, GATHERING_PLACE, MAXIMUM_PEOPLE, MINIMUM_ORDER_AMOUNT, TITLE)
values(3L, '이종렬', now(), 0, 0, '글로벌관', 10, 10000, '아이 니드 카페인');

insert into ROOM(ROOM_ID, CREATED_BY, CREATED_DATE, CURR_NUM_OF_PEOPLE, CURRENT_AMOUNT, FIGURE, GATHERING_DETAIL_PLACE, GATHERING_PLACE
, MAXIMUM_PEOPLE, MINIMUM_ORDER_AMOUNT, ROOM_STATUS, TITLE)
values(272, '나는 문어', now(), 1, 5500, 1, '글로벌관 1층', '경북 구미시 대학로 61 (양호동)', 4, 9000, 'RECRUIT', '맘터 같이 먹을 사람??');
insert into ROOM(ROOM_ID, CREATED_BY, CREATED_DATE, CURR_NUM_OF_PEOPLE, CURRENT_AMOUNT, FIGURE, GATHERING_DETAIL_PLACE, GATHERING_PLACE
, MAXIMUM_PEOPLE, MINIMUM_ORDER_AMOUNT, ROOM_STATUS, TITLE)
values(273, '수민', now(), 1, 7000, 1, '테크노관 분수 앞', '경북 구미시 대학로 61 (양호동)', 4, 20000, 'RECRUIT', '국밥 같이 먹자!');



-- 유저 데이터
insert into USER(USER_ID, EMAIL, JOIN_ROOM, MONEY, NICKNAME, PHONE_NUMBER, PW, ROOM_ID, TOTAL_AMOUNT)
values(4L, 'aa@naver.com', false, 0, '김민수', '01012345678', 'pw1', null, 0);
insert into USER(USER_ID, EMAIL, JOIN_ROOM, MONEY, NICKNAME, PHONE_NUMBER, PW, ROOM_ID, TOTAL_AMOUNT)
values(5L, 'bb@naver.com', false, 0, '민수킴', '01012345678', 'pw2', null, 0);
insert into USER(USER_ID, EMAIL, JOIN_ROOM, MONEY, NICKNAME, PHONE_NUMBER, PW, ROOM_ID, TOTAL_AMOUNT)
values(6L, 'cc@naver.com', false, 0, '이종렬', '01012345678', 'pw3', null, 0);
