
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace